name: bloc_example
description: "Use -bloc- in your app (FLUTTER)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  http: ^1.1.2
  get_storage: ^2.1.1


  #ICON APP PACKAGE
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_bloc.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne-Regular.ttf

    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf

